### ISSUE TITLE
gcc-6.3.0 build error on Fedora 27

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-easyconfigs#5758] opened 2018-01-31 15:55 UTC
I was running a test build for #5735 and it failed at the first hurdle with this error for `gcc-6.3.0`:
```
/dev/shm/GCCcore/6.3.0/dummy-/gcc-6.3.0/stage1_obj/./gcc/xgcc -B/dev/shm/GCCcore/6.3.0/dummy-/gcc-6.3.0/stage1_obj/./gcc/ -B/dev/shm/GCCcore/6.3.0/dummy-/GCC_stage1_eb/x86_64-pc-linux-gnu/bin/ -B/dev/shm/GCCcore/6.3.0/dummy-/GCC_stage1_eb/x86_64-pc-linux-gnu/lib/ -isystem /dev/shm/GCCcore/6.3.0/dummy-/GCC_stage1_eb/x86_64-pc-linux-gnu/include -isystem /dev/shm/GCCcore/6.3.0/dummy-/GCC_stage1_eb/x86_64-pc-linux-gnu/sys-include    -g -O2 -O2  -g -O2 -DIN_GCC    -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -mlong-double-80 -DUSE_ELF_SYMVER -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fpic -mlong-double-80 -DUSE_ELF_SYMVER -I. -I. -I../.././gcc -I../../../libgcc -I../../../libgcc/. -I../../../libgcc/../gcc -I../../../libgcc/../include -I../../../libgcc/config/libbid -DENABLE_DECIMAL_BID_FORMAT -DHAVE_CC_TLS  -DUSE_TLS -o unwind-sjlj.o -MT unwind-sjlj.o -MD -MP -MF unwind-sjlj.dep -fexceptions -c ../../../libgcc/unwind-sjlj.c -fvisibility=hidden -DHIDE_EXPORTS
In file included from ../../../libgcc/unwind-dw2.c:401:0:
./md-unwind-support.h: In function ‘x86_64_fallback_frame_state’:
./md-unwind-support.h:65:47: error: dereferencing pointer to incomplete type ‘struct ucontext’
       sc = (struct sigcontext *) (void *) &uc_->uc_mcontext;
                                               ^~
make[2]: *** [../../../libgcc/shared-object.mk:14: unwind-dw2.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/dev/shm/GCCcore/6.3.0/dummy-/gcc-6.3.0/stage1_obj/x86_64-pc-linux-gnu/libgcc'
make[1]: *** [Makefile:14075: all-target-libgcc] Error 2
make[1]: Leaving directory '/dev/shm/GCCcore/6.3.0/dummy-/gcc-6.3.0/stage1_obj'
make: *** [Makefile:888: all] Error 2
```

**Comment by floringogianu** [comment] 2018-04-25 09:03
same on `ubuntu 17.10`

**Comment by seb45tian** [comment] 2018-07-11 10:07
I run into the same problem when building the foss-2018a toolchain when getting to GCC-6.4.0. I think this is related to this issue: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81712

The problem is, that `struct ucontext` doesn't exist anymore in glibc2.26 , see  https://sourceware.org/glibc/wiki/Release/2.26#Removal_of_.27struct_ucontext.27

This was fixed for GCC-7XX and also backported to the 5 and 6 series but only comes with updated versions 5.5 and 6.5. I would suggest to at least include 6.5 in the next foos-2018b toolchain revision.

As a workaround to compile gcc code with glibc 2.26+ one can change `struct ucontext` to `ucontext_t` in the gcc source as suggested here: https://github.com/suaefar/ryzen-test/issues/6 , but I haven't tried it, yet.

**Comment by boegel** [comment] 2018-07-11 10:20
We fixed this for GCCcore 6.4.0 in #6432 (+ #6495)

`foss/2018b` includes GCC(core) 7.3.0, as far as I know there's no problem there.

**Comment by boegel** [comment] 2018-07-11 11:06
It's likely that the patch in #6432 also works for GCC 6.3.0, can someone try this?

**Comment by seb45tian** [comment] 2018-07-11 11:09
Ah ok I see. Mmmm... but why is my build failing? Also when I check the supposed to be patched file `libgcc/config/aarch64/linux-unwind.h` in the build directory, it is not patched. Still using `struct ucontext uc`   What am I missing here? I’m on Ubuntu 18.04 btw.

**Comment by boegel** [comment] 2018-07-11 17:44
@seb45tian #6432 is not included yet in the latest EasyBuild release (3.6.1), but will be in the next one (3.6.2), which should be available shortly (in a couple of hours even, if all goes well...).

**Comment by seb45tian** [comment] 2018-07-11 20:18
Ah thanks for the hint, and also the patch. Think this one can be closed then. 
Cheers

**Comment by boegel** [comment] 2018-07-11 20:33
Well, the issue is still there for GCC 6.3.0, so I'll leave it up to @verdurin whether we can close this or not... Should we make the effort of also applying the patch in the GCCcore 6.3.0 easyconfig?

**Comment by boegel** [comment] 2018-12-14 13:07
@verdurin Is it worth the trouble to also try to fix this for GCCcore 6.3.0?

**Comment by boegel** [comment] 2019-01-19 11:34
@verdurin re-ping...

**Comment by boegel** [comment] 2019-11-11 20:49
I'm going to assume this is no longer relevant...

**Closed by boegel** 2019-11-11 20:49 UTC
Labels: problem report
