### ISSUE TITLE
Togl looks for the Tcl and Tk *build* folders and fails if those paths are not accessible

### ISSUE THREAD

**Issue by hrnagel** [easybuilders/easybuild-easyconfigs#10657] opened 2020-05-20 10:30 UTC
When I try to install Togl:

$ eb Togl-2.0-GCCcore-8.3.0.eb --robot

I get these two lines in the log file:

checking for Tcl private include files... Using srcdir found in tclConfig.sh: /cluster/work/users/vegarde/build/Tcl/8.6.9/GCCcore-8.3.0/tcl8.6.9
checking for Tk private include files... Using srcdir found in tkConfig.sh: /cluster/work/users/vegarde/build/Tk/8.6.9/GCCcore-8.3.0/tk8.6.9

I am not the user vegarde and all files older than 21 days are automatically deleted on work. These files were therefore deleted more than half a year ago, but even if they were there I would probably still not have access to them. The only way for us to install Togl is therefore to ask vegarde to recreate the content in those two directories and then have him install Togl. Why does Togl depend upon the source-directory for Tcl and Tk?

**Comment by migueldiascosta** [comment] 2020-05-21 03:21
yeah, `Togl`'s `configure` script looks into the `Tcl` and `Tk` src ( in this case, build) dirs but it's really not necessary, and there is a patch that skips the actual check - @hrnagel are you sure this is really why you can't install `Togl`? Can you share the log in a gist?

**Comment by hrnagel** [comment] 2020-05-21 07:02
I have uploaded the log file: https://gist.github.com/hrnagel/0f1fa91baa3925355015c3a97350aff8

**Comment by migueldiascosta** [comment] 2020-05-21 07:06
@hrnagel I see, that path is still being added to the include paths and fails because of lack of permissions, even though accessing that path is not necessary. let me see if I can reproduce and improve the patch

**Comment by hrnagel** [comment] 2020-05-21 07:07
> That's pretty strange indeed...
> 
> What happens if you try to reinstall `Tcl` and `Tk`, is that's an option?
> Maybe they were installed and later moved or something like that?

We would have to wait until monday to get an answer to those questions.

**Comment by migueldiascosta** [comment] 2020-05-21 07:42
@hrnagel can you try with #10662? 

(e.g., `eb --from-pr 10662 -dr`, or download the new easyconfig and configure patch if github integration is not available)

**Comment by hrnagel** [comment] 2020-05-21 08:09
`eb --from-pr 10662 -dr` worked without any problems.

**Comment by boegel** [comment] 2020-05-23 16:06
Fixed with #10662, so closing... Thanks for the fix @migueldiascosta!

**Closed by boegel** 2020-05-23 16:06 UTC
Labels: problem report
