### ISSUE TITLE
Build of M4 fails with glibc 2.28

### ISSUE THREAD

**Issue by robertschade** [easybuilders/easybuild-easyconfigs#7383] opened 2019-01-08 14:51 UTC
Due to changes in glibc 2.28, see
https://lists.gnu.org/r/bug-gnulib/2018-03/msg00000.html and https://www.sourceware.org/ml/libc-alpha/2018-08/msg00003.html, M4-1.4.18 does not build on systems with glibc 2.28.
This issue can be fixed similar to how it is fixed in gnulibs: https://github.com/coreutils/gnulib/commit/4af4a4a71827c0bc5e0ec67af23edef4f15cee8e#diff-5bcce8ce55246264586c4aed2a45ff89
This problem will become urgend once more distros change from glibc 2.27 to 2.28.

[M4-1.4.18.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/2737213/M4-1.4.18.txt)
[M4_glibc_2.28.patch.txt](https://github.com/easybuilders/easybuild-easyconfigs/files/2737214/M4_glibc_2.28.patch.txt)

**Comment by boegel** [comment] 2019-01-19 12:58
closing this since the issue is fixed via #7384, thanks again @robertschade!

**Closed by boegel** 2019-01-19 12:58 UTC
Labels: problem report
