### ISSUE TITLE
compilation fail bison 3.0.4, EasyBuild 3.9.3, fedora 30 

### ISSUE THREAD

**Issue by alchemroz** [easybuilders/easybuild-easyconfigs#8673] opened 2019-08-06 11:14 UTC
I tried to install 
eb --software-name=QuantumESPRESSO --toolchain=intel,2018b --robot 

I got an error when building Bison 3.0.4

lib/fseterr.c: In function 'fseterr':
lib/fseterr.c:77:3: error: #error "Please port gnulib fseterr.c to your platform
! Look at the definitions of ferror and clearerr on your system, then report thi
s to bug-gnulib."
   77 |  #error "Please port gnulib fseterr.c to your platform! Look at the definitions of ferror and clearerr on your system, then report this to bug-gnulib."

I tried to google the problem, they suggested to install 

sudo dnf install libunistring-devel

I did it but it did not solve the problem. 

Bests,
Simone

**Comment by boegel** [comment] 2019-08-06 13:46
@alchemroz The problem is very similar to the one you were hitting with `M4` (cfr. #8633)

Should be fixed in #8675, so please try installing `Bison` using `eb --from-pr 8675 Bison-3.0.4.eb` to pull in the fixed easyconfig file, let us know if that worked...

**Comment by alchemroz** [comment] 2019-08-06 13:53
Dear @boegel thanks for the suggestion. I just tried, it worked nice

COMPLETED: Installation ended successfully

**Comment by boegel** [comment] 2019-08-06 13:57
Excellent!

Do let us know if you hit any other problems... You'll likely hit the same problem again when `M4` and `Bison` are installed with a non-dummy toolchain, you can use the same trick using `--from-pr` to dance around it when using EasyBuild v3.9.3 until EasyBuild v3.9.4 is released.

You'll see multiple installations of `M4` and `Bison` happen because of the bootstrap procedure that EasyBuild does for `binutils` and `GCCcore`, where it first builds a `binutils` with the system compiler (by using the `dummy` toolchain), which it then uses to build `GCCcore`, after which it builds another `binutils` using `GCCcore` as toolchain (to avoid relying on the system GCC or binutils for subsequent software builds).

I'll go ahead and close this issue, since the fix in #8675 is confirmed, don't hesitate to report other problems you may be hitting!

**Closed by boegel** 2019-08-06 13:57 UTC
Labels: bug report
