### ISSUE TITLE
Build error for FTGL-2.1.3-rc5-GCCcore-10.2.0

### ISSUE THREAD

**Issue by JuergenUniVie** [easybuilders/easybuild-easyconfigs#15964] opened 2022-08-04 11:10 UTC
get the following error (RHEL8):

FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightfv'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightfv'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightfv'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightfv'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glEnable'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialfv'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialfv'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialfv'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialfv'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialf'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glColor4fv'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightModeli'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glColorMaterial'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glEnable'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function setUpLighting(): error: undefined reference to 'glEnable'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glDisable'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glEnable'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBlendFunc'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glColor3f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBegin'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glVertex3f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glVertex3f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glVertex3f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glVertex3f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glEnd'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glColor3f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBegin'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glEnd'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glTranslatef'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glColor3f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glPointSize'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBegin'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glEnd'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glColor3f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBegin'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glEnd'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontInfo(): error: undefined reference to 'glMatrixMode'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontInfo(): error: undefined reference to 'glLoadIdentity'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontInfo(): error: undefined reference to 'gluOrtho2D'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontInfo(): error: undefined reference to 'glMatrixMode'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontInfo(): error: undefined reference to 'glLoadIdentity'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontInfo(): error: undefined reference to 'glRasterPos2f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontInfo(): error: undefined reference to 'glRasterPos2i'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontInfo(): error: undefined reference to 'glRasterPos2f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function renderFontInfo(): error: undefined reference to 'glRasterPos2f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glDisable'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glTranslatef'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glPushMatrix'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glPopMatrix'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glPushMatrix'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glPopMatrix'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glDisable'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glNormal3f'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glDisable'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glBindTexture'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function do_display(): error: undefined reference to 'glBindTexture'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function SetCamera(): error: undefined reference to 'glMatrixMode'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function SetCamera(): error: undefined reference to 'glLoadIdentity'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function SetCamera(): error: undefined reference to 'gluPerspective'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function SetCamera(): error: undefined reference to 'glMatrixMode'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function SetCamera(): error: undefined reference to 'glLoadIdentity'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function SetCamera(): error: undefined reference to 'gluLookAt'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function SetCamera(): error: undefined reference to 'gluOrtho2D'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function display(): error: undefined reference to 'glClear'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function display(): error: undefined reference to 'glPushMatrix'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function display(): error: undefined reference to 'glPopMatrix'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function display(): error: undefined reference to 'glRasterPos2i'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function display(): error: undefined reference to 'glTranslatef'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myReshape(int, int): error: undefined reference to 'glViewport'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glClear'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glClearColor'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glFrontFace'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glShadeModel'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glPolygonOffset'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glGenTextures'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glBindTexture'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glTexParameteri'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glTexParameteri'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glTexParameteri'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glTexParameteri'
FTGLDemo-FTGLDemo.o:FTGLDemo.cpp:function myinit(char const*): error: undefined reference to 'glTexImage2D'
tb.o:tb.c:function tbMatrix: error: undefined reference to 'glMultMatrixf'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:319: FTGLDemo] Fehler 1
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightfv'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightfv'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightfv'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightfv'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glEnable'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialfv'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialfv'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialfv'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialfv'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glMaterialf'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glColor4fv'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glLightModeli'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glEnable'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glColorMaterial'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glEnable'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glEnable'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function setUpLighting(): error: undefined reference to 'glShadeModel'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glDisable'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glDisable'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBlendFunc'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glColor3f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBegin'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glVertex3f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glVertex3f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glVertex3f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glVertex3f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glEnd'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glColor3f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBegin'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glEnd'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glColor3f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glPointSize'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBegin'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glBegin'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glEnd'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glEnd'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontmetrics(): error: undefined reference to 'glColor3f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontInfo(): error: undefined reference to 'glMatrixMode'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontInfo(): error: undefined reference to 'glLoadIdentity'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontInfo(): error: undefined reference to 'gluOrtho2D'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontInfo(): error: undefined reference to 'glMatrixMode'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontInfo(): error: undefined reference to 'glLoadIdentity'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontInfo(): error: undefined reference to 'glRasterPos2f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontInfo(): error: undefined reference to 'glRasterPos2i'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontInfo(): error: undefined reference to 'glRasterPos2f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function renderFontInfo(): error: undefined reference to 'glRasterPos2f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function do_display(): error: undefined reference to 'glDisable'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function do_display(): error: undefined reference to 'glDisable'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function do_display(): error: undefined reference to 'glNormal3f'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function SetCamera(): error: undefined reference to 'glMatrixMode'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function SetCamera(): error: undefined reference to 'glLoadIdentity'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function SetCamera(): error: undefined reference to 'gluPerspective'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function SetCamera(): error: undefined reference to 'glMatrixMode'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function SetCamera(): error: undefined reference to 'glLoadIdentity'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function SetCamera(): error: undefined reference to 'gluLookAt'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function SetCamera(): error: undefined reference to 'gluOrtho2D'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function display(): error: undefined reference to 'glClear'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function display(): error: undefined reference to 'glTranslatef'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function display(): error: undefined reference to 'glPushMatrix'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function display(): error: undefined reference to 'glPopMatrix'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function display(): error: undefined reference to 'glRasterPos2i'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function display(): error: undefined reference to 'glTranslatef'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function myReshape(int, int): error: undefined reference to 'glViewport'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function myinit(int): error: undefined reference to 'glClear'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function myinit(int): error: undefined reference to 'glClearColor'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function myinit(int): error: undefined reference to 'glFrontFace'
FTGLMFontDemo-FTGLMFontDemo.o:FTGLMFontDemo.cpp:function myinit(int): error: undefined reference to 'glPolygonOffset'
tb.o:tb.c:function tbMatrix: error: undefined reference to 'glMultMatrixf'
collect2: error: ld returned 1 exit status

any ideas?

Thanks
Juergen

**Comment by Micket** [comment] 2022-08-08 20:41
I'm unable to reproduce any issue building this on Rocky Linux 8.5.

I don't think we can say anything without more of the log (as a gist)

**Comment by JuergenUniVie** [comment] 2022-08-09 06:59
[easybuild-FTGL-2.1.3-rc5-20220809.085436.aFVfr.log](https://github.com/easybuilders/easybuild-easyconfigs/files/9287796/easybuild-FTGL-2.1.3-rc5-20220809.085436.aFVfr.log)

**Comment by branfosj** [comment] 2022-08-09 09:33
My build
```
checking GL/gl.h usability... yes
checking GL/gl.h presence... yes
checking for GL/gl.h... yes
checking for OpenGL framework (Darwin-specific)... no
checking for GL library... yes
checking GL/glu.h usability... yes
checking GL/glu.h presence... yes
checking for GL/glu.h... yes
checking for GLU version >= 1.2... yes
checking for GLU library... yes
checking GL/glut.h usability... no
checking GL/glut.h presence... no
checking for GL/glut.h... no
checking GLUT/glut.h usability... no
checking GLUT/glut.h presence... no
checking for GLUT/glut.h... no
configure: WARNING: GLUT headers not available, example program won't be compiled.
```

@JuergenUniVie build
```
checking GL/gl.h usability... yes
checking GL/gl.h presence... yes
checking for GL/gl.h... yes
checking for OpenGL framework (Darwin-specific)... no
checking for GL library... yes
checking GL/glu.h usability... yes
checking GL/glu.h presence... yes
checking for GL/glu.h... yes
checking for GLU version >= 1.2... yes
checking for GLU library... yes
checking GL/glut.h usability... yes
checking GL/glut.h presence... yes
checking for GL/glut.h... yes
checking for GLUT library... yes
```

So, I expect that means an OS installed package is being picked up and causing the examples (/demos to be built).

The error seen was in building a demo, but In my build this section does nothing:
```
Making all in demo
make[2]: Entering directory '/dev/shm/branfosj/build-up-EL8/FTGL/2.1.3-rc5/GCCcore-10.2.0/ftgl-2.1.3~rc5/demo'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/dev/shm/branfosj/build-up-EL8/FTGL/2.1.3-rc5/GCCcore-10.2.0/ftgl-2.1.3~rc5/demo'
```

**Comment by Micket** [comment] 2022-08-09 10:09
Errors are reproducible if you add `('freeglut', '3.2.1'),`  dep so that it tries to build the demos. 
I see no convenient configure flag to intentionally exclude this

**Comment by JuergenUniVie** [comment] 2022-08-11 06:35
Thanks for the suggestion! I removed the freeglut-devel package and now it works :-)

**Comment by Micket** [comment] 2022-08-12 15:37
I don't see anything practical worth doing in EB to prevent this apart from removing devel packages from the OS, so i'll just close this issue

**Closed by Micket** 2022-08-12 15:37 UTC
Labels: problem report
