### ISSUE TITLE
Can't locate ExtUtils/Config.pm

### ISSUE THREAD

**Issue by jacorvar** [easybuilders/easybuild-easyconfigs#4999] opened 2017-08-10 07:39 UTC
Hi,

I've tried to install Perl-5.22.1-foss-2016a.eb but it complains:

```
== building and installing Perl/5.22.1-foss-2016a...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== installing extension Config::General 2.60 (1/219)...
== installing extension File::Listing 6.04 (2/219)...
== installing extension ExtUtils::InstallPaths 0.011 (3/219)...
== installing extension ExtUtils::Helpers 0.022 (4/219)...
== installing extension Test::Harness 3.36 (5/219)...
== installing extension ExtUtils::Config 0.008 (6/219)...
== installing extension Module::Build::Tiny 0.039 (7/219)...
== FAILED: Installation ended unsuccessfully (build directory: /usr/local/easybuild/.local/easybuild/build/Perl/5.22.1/foss-2016a): build failed (first 300 chars): cmd " perl Build.PL --prefix /usr/local/easybuild/.local/easybuild/software/Perl/5.22.1-foss-2016a " exited with exitcode 2 and output:
Can't locate ExtUtils/Config.pm in @INC (you may need to install the ExtUtils::Config module) (@INC contains: lib /usr/local/easybuild/.local/easybuild/software/Per
== Results of the build can be found in the log file(s) /tmp/eb-5LmJFm/easybuild-Perl-5.22.1-20170810.083919.HRTUF.log
ERROR: Build of /usr/local/easybuild/.local/easybuild/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.3.1-py2.7.egg/easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb failed (err: 'build failed (first 300 chars): cmd " perl Build.PL --prefix /usr/local/easybuild/.local/easybuild/software/Perl/5.22.1-foss-2016a " exited with exitcode 2 and output:\nCan\'t locate ExtUtils/Config.pm in @INC (you may need to install the ExtUtils::Config module) (@INC contains: lib /usr/local/easybuild/.local/easybuild/software/Per')
```

**Comment by boegel** [comment] 2017-08-10 09:23
@jacorvar Hmm, this should work out of the box... Can you upload the log file somewhere (and preferably make it a debug log, using `eb --debug`)?

**Comment by jacorvar** [comment] 2017-08-10 11:10
```
== temporary log file in case of crash /tmp/eb-78skzD/easybuild-IsIqaA.log
== processing EasyBuild easyconfig /usr/local/easybuild/.local/easybuild/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.3.1-py2.7.egg/easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb
== building and installing Perl/5.22.1-foss-2016a...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== installing extension Config::General 2.60 (1/219)...
== installing extension File::Listing 6.04 (2/219)...
== installing extension ExtUtils::InstallPaths 0.011 (3/219)...
== installing extension ExtUtils::Helpers 0.022 (4/219)...
== installing extension Test::Harness 3.36 (5/219)...
== installing extension ExtUtils::Config 0.008 (6/219)...
== installing extension Module::Build::Tiny 0.039 (7/219)...
== FAILED: Installation ended unsuccessfully (build directory: /usr/local/easybuild/.local/easybuild/build/Perl/5.22.1/foss-2016a): build failed (first 300 chars): cmd " perl Build.PL --prefix /usr/local/easybuild/.local/easybuild/software/Perl/5.22.1-foss-2016a " exited with exitcode 2 and output:
Can't locate ExtUtils/Config.pm in @INC (you may need to install the ExtUtils::Config module) (@INC contains: lib /usr/local/easybuild/.local/easybuild/software/Per
== Results of the build can be found in the log file(s) /tmp/eb-78skzD/easybuild-Perl-5.22.1-20170810.123024.wKGFy.log
ERROR: Build of /usr/local/easybuild/.local/easybuild/software/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.3.1-py2.7.egg/easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb failed (err: 'build failed (first 300 chars): cmd " perl Build.PL --prefix /usr/local/easybuild/.local/easybuild/software/Perl/5.22.1-foss-2016a " exited with exitcode 2 and output:\nCan\'t locate ExtUtils/Config.pm in @INC (you may need to install the ExtUtils::Config module) (@INC contains: lib /usr/local/easybuild/.local/easybuild/software/Per')
```

**Comment by jacorvar** [comment] 2017-08-10 11:16
[easybuild-IsIqaA.log.gz](https://github.com/easybuilders/easybuild-easyconfigs/files/1214661/easybuild-IsIqaA.log.gz)

**Comment by boegel** [comment] 2017-08-10 13:32
OK, so even though `ExtUtils::Config` was installed shortly before, it's not being found during the installation of `Module::Build::Tiny`...

Can you check whether you have a `Config.pm` in `/usr/local/easybuild/.local/easybuild/software/software/Perl/5.22.1-foss-2016a/lib/perl5/site_perl/5.22.1/ExtUtils`?

I see no problems popping up during the installation of `ExtUtils::Config`, so it should be there. And if it's there, then it shouldn't be complaining that it can't find it, since that path is included in the search path used by Perl (see the `@INC contains` in the error message)...

Do you have `ExtUtils-Config` package installed centrally? Check with `rpm -qa | grep ExtUtils`.

**Comment by jacorvar** [comment] 2017-08-10 15:31
There's no `ExtUtils` subdirectory inside `/usr/local/easybuild/.local/easybuild/software/software/Perl/5.22.1-foss-2016a/lib/perl5/site_perl/5.22.1`, and no `Config.pm` file inside `/usr/local/easybuild/.local/easybuild/software/Perl/5.22.1-foss-2016a/lib/perl5/5.22.1/ExtUtils/` either.

rpm -qa | grep ExtUtils gives no output and I could find the following Config.pm files related to ExtUtils only:
```
/usr/local/easybuild/.local/easybuild/software/Perl/5.22.1-foss-2016a/lib/perl5/5.22.1/ExtUtils/MakeMaker/Config.pm
/usr/local/easybuild/.local/easybuild/build/Perl/5.22.1/foss-2016a/ExtUtilsConfig/ExtUtils-Config-0.008/lib/ExtUtils/Config.pm
/usr/local/easybuild/.local/easybuild/build/Perl/5.22.1/foss-2016a/ExtUtilsConfig/ExtUtils-Config-0.008/blib/lib/ExtUtils/Config.pm
/usr/local/easybuild/.local/easybuild/build/Perl/5.22.1/foss-2016a/perl-5.22.1/lib/ExtUtils/MakeMaker/Config.pm
/usr/local/easybuild/.local/easybuild/build/Perl/5.22.1/foss-2016a/perl-5.22.1/cpan/ExtUtils-MakeMaker/lib/ExtUtils/MakeMaker/Config.pm
/usr/local/easybuild/.local/easybuild/build/Perl/5.22.1/foss-2016a/perl-5.22.1/cpan/ExtUtils-MakeMaker/t/testdata/reallylongdirectoryname/arch1/Config.pm
/usr/local/easybuild/.local/easybuild/build/Perl/5.22.1/foss-2016a/perl-5.22.1/cpan/ExtUtils-MakeMaker/t/testdata/reallylongdirectoryname/arch2/Config.pm
```

**Comment by boegel** [comment] 2017-08-10 16:06
OK, so for some reason even though the installation of `ExtUtils::Config` seems to work fine, some stuff is not getting installed...

Here's the output of `make install` for `ExtUtils::Config` from your log:

```
== 2017-08-10 13:02:36,653 run.py:449 INFO cmd " make install " exited with exitcode 0 and output:
Manifying 1 pod document
Installing /usr/local/easybuild/.local/easybuild/software/Perl/5.22.1-foss-2016a/man/man3/ExtUtils::Config.3
Appending installation info to /usr/local/easybuild/.local/easybuild/software/Perl/5.22.1-foss-2016a/lib/perl5/5.22.1/x86_64-linux-thread-multi/perllocal.pod

```

Here's the output I'm seeing (same easyconfig file):

```
== 2017-07-10 22:58:06,682 run.py:449 INFO cmd " make install " exited with exitcode 0 and output:
Manifying 1 pod document
Installing /tmp/software/Perl/5.22.1-foss-2016a/lib/perl5/site_perl/5.22.1/ExtUtils/Config.pm
Installing /tmp/software/Perl/5.22.1-foss-2016a/man/man3/ExtUtils::Config.3
Appending installation info to /tmp/software/Perl/5.22.1-foss-2016a/lib/perl5/5.22.1/x86_64-linux-thread-multi/perllocal.pod

```

At least it's admitting to being guilty in your case, but I honestly have no idea why it figures it's not required to installing `ExtUtils/Config.pm`...

**Comment by jacorvar** [comment] 2018-05-01 16:40
Hi @boegel , I installed perl centrally, so `rpm -qa | grep ExtUtils` gives the following:
```
perl-ExtUtils-Manifest-1.61-244.el7.noarch
perl-ExtUtils-MakeMaker-6.68-3.el7.noarch
perl-ExtUtils-ParseXS-3.18-2.el7.noarch
perl-ExtUtils-Install-1.58-291.el7.noarch
```
I've tried again to install `Perl-5.22.1-foss-2016b.eb` and `Perl-5.26.1-foss-2018a.eb`. I get the same error.
`/usr/local/easybuild/.local/easybuild/software/software/Perl/5.22.1-foss-2016b/lib/perl5/site_perl/5.22.1/ExtUtil` directory does not exist, but `/usr/local/easybuild/.local/easybuild/software/Perl/5.22.1-foss-2016b/lib/perl5/*5.26.1*/ExtUtils/`. However, there is no `Config.pm` file in that directory. Same happens to 5.26.1-foss-2018a version.
Could you guess what is happening?

Thanks

**Comment by robertschade** [comment] 2019-02-11 12:41
I experience the same problem with Perl-5.28.0-GCCcore-7.3.0.eb

== FAILED: Installation ended unsuccessfully (build directory: /scratch/pc2-mitarbeiter/rschade/easybuild/build/Perl/5.28.0/GCCcore-7.3.0): build failed (first 300 chars): cmd " perl Build.PL --prefix /scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0 " exited with exit code 2 and output:
Can't locate ExtUtils/Config.pm in @INC (you may need to install the ExtUtils::Config module) (@INC contains: lib /scratch/pc2-mitarbeiter/rschade/easybuil

**Comment by robertschade** [comment] 2019-02-11 13:16
btw, ExtUtils/Config.pm is being build but not found ("installing extension ExtUtils::Config 0.008 (6/288)...")

**Comment by robertschade** [comment] 2019-02-11 15:07
The comamnd:

` "/scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0/bin/perl" -MExtUtils::Install -e 'install([ from_to => {@ARGV}, verbose => '\''0'\'', uninstall_shadows => '\''0'\'', dir_mode => '\''755'\'' ]);' -- \
        read "/scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0/lib/perl5/site_perl/5.28.0/x86_64-linux-thread-multi/auto/ExtUtils/Config/.packlist" \
        write "/scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0/lib/perl5/site_perl/5.28.0/x86_64-linux-thread-multi/auto/ExtUtils/Config/.packlist" \
        "blib/lib" "/scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0/lib/perl5/site_perl/5.28.0" \
        "blib/arch" "/scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0/lib/perl5/site_perl/5.28.0/x86_64-linux-thread-multi" \
        "blib/bin" "/scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0/bin" \
        "blib/script" "/scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0/bin" \
        "blib/man1" "/scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0/man/man1" \
        "blib/man3" "/scratch/pc2-mitarbeiter/rschade/easybuild/software/Perl/5.28.0-GCCcore-7.3.0/man/man3"`

**Comment by boegel** [comment] 2019-02-12 07:42
@robertschade Can you check the logic in the `Makefile`, and see if you can spot a condition that would explain why `Config.pm` doesn't get installed?

**Comment by robertschade** [comment] 2019-02-12 14:03
Right now, for us this looks to be an issue of the underlying file system (Beegfs). 
The problem happens is file are written by "make" and then directly afterwards accessed by "make install" during the installation of the perl modules. "make install" doesn't find all files and, hence, doesn't install them properly.

Putting  a few cmd_run("sync") in easybuild/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_easyblocks-3.8.1-py2.7.egg/easybuild/easyblocks/generic/perlmodule.py 
around the ConfigureMake-calls causes the installation to proceed beyond the point where it failed before.

Steps to reproduce: [eb_test.log](https://github.com/easybuilders/easybuild-easyconfigs/files/2855898/eb_test.log)

Machine: CentOS 7.2, Xeon E5-2670 , Easybuild 3.8.1

- On beegfs 2015-08 r15: build of Perl-5.28.0-GCCcore-7.3.0.eb fails [beegfs.log](https://github.com/easybuilders/easybuild-easyconfigs/files/2856132/beegfs.log)

- On ext4 (same machine, same day): builds perfectly [ext4.log](https://github.com/easybuilders/easybuild-easyconfigs/files/2855874/ext4.log)

I conclude that this issue is due to the underlying file system and not really an issue of easybuild.

**Comment by robertschade** [comment] 2019-02-12 14:16
@boegel The logic of the Makefile is proper. Make copies some files, e.g. Config.pm in to a directory blib/lib/. Then "make install" is supposed to copy these files somewhere else. However, when executed on our old Beegfs, "make install" does not see the files that have been copied by "make" and, hence, does not copy them. 
However, when one looks later, these files are in blib/lib, so it was very confusing why "make install" did not copy them. Indeed, if you run the commands from "make install" later, the files are being copied.

This was the hint for me to expect a timing issue with the underlying file system.

**Comment by robertschade** [comment] 2019-02-12 14:18
However, we can't diagnose the beegfs issue further, because this is a production installation that otherwise works perfectly.

**Comment by robertschade** [comment] 2019-02-12 14:22
@boegel I have also set up a virtual machine with nearly the same software installation (CentOS 7.2, environment-modules) as the system where the installation failed. In the virtual machine, using an ext4-file system, the installation works without problems.

**Comment by omula** [comment] 2019-02-21 21:38
@robertschade you can use a different filesystem as this only affects the building phase.
In my case I got it compiled with `export EASYBUILD_BUILDPATH=/dev/shm`

**Comment by boegel** [comment] 2019-02-23 15:25
Interesting analysis!

I remember running into similar issues with GPFS at some point, I think it was with OCaml, but the problem disappeared after an update.

@robertschade Do you think it's worth adding the `sync` command to the `PerlModule` easyblock to dance around this? Or maybe a simple "sleep" suffices?

**Comment by robertschade** [comment] 2019-02-25 12:35
As noted in my previous comment (https://github.com/easybuilders/easybuild-easyconfigs/issues/4999#issuecomment-462770844):

> Putting a few cmd_run("sync") in easybuild/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_easyblocks-3.8.1-py2.7.egg/easybuild/easyblocks/generic/perlmodule.py
around the ConfigureMake-calls causes the installation to proceed beyond the point where it failed before.

With some file system syncs in perlmodule.py the installation of Module::Build::Tiny works, but fails later for a different module. That is why I have not suggested syncs as a solution as they do not reliably solve the problem for our BeeGFS.

**Comment by boegel** [comment] 2019-02-26 08:36
OK, so is there anything else we can do in EasyBuild to help deal with this?

If not, we should close this issue; it can serve as a record of what the underlying cause was and provide hints to others hitting this problem?

**Comment by robertschade** [comment] 2019-02-26 09:42
I don't think so. I agree with closing this issue.

**Closed** 2019-02-26 20:23 UTC
Labels: problem report

**Comment by andreas-h** [comment] 2019-07-30 13:36
This is just another data point: I was struck by the same problem (this time on NFS instead of BeeGFS).  I could solve this by using `/dev/shm` as `EASYBUILD_BUILDPATH`.

How do you deal with little issues like this?  Maybe a note in the easyconfig file?

**Comment by boegel** [comment] 2019-08-07 20:50
@andreas-h I'm not sure a note in the easyconfig file would help much... Not sure how to expose this problem better.
