### ISSUE TITLE
PyQt-4.12-foss-2016b-Python-2.7.12.eb dont't build QtOpenGL.so

### ISSUE THREAD

**Issue by iotaka** [easybuilders/easybuild-easyconfigs#5000] opened 2017-08-10 09:29 UTC
Hi, on my system I find this modules in

easybuild/software/PyQt/4.12-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/PyQt4/

Qt.so
QtCore.so
QtDeclarative.so
QtDesigner.so
QtGui.so
QtHelp.so
QtMultimedia.so
QtNetwork.so
QtScript.so
QtScriptTools.so
QtSql.so
QtSvg.so
QtTest.so
QtWebKit.so
QtXml.so
QtXmlPatterns.so

I need also: **QtOpenGL.so**. From the official DOC of PyQT "Normally all PyQt4 modules are enabled and are built if the corresponding Qt library can be found."

I added the option configopts += " --enable=QtOpenGL" in .eb end rebuilt the module. As expected now I have only:

Qt.so
QtOpenGL.so

So I added all the modules find here http://pyqt.sourceforge.net/Docs/PyQt4/installation.html#configuring-with-configuration-files

configopts += " --enable=QtCore"
#configopts += " --enable=QtDBus"
configopts += " --enable=QtDeclarative"
configopts += " --enable=QtDesigner"
configopts += " --enable=QtGui"
configopts += " --enable=QtHelp"
configopts += " --enable=QtMultimedia"
#configopts += " --enable=QtMultimediaWidgets"
configopts += " --enable=QtNetwork"
configopts += " --enable=QtOpenGL"
#configopts += " --enable=QtPrintSupport"
#configopts += " --enable=QtQml"
#configopts += " --enable=QtQuick"
configopts += " --enable=QtScript"
configopts += " --enable=QtScriptTools"
#configopts += " --enable=QtSensors"
#configopts += " --enable=QtSerialPort"
configopts += " --enable=QtSql"
configopts += " --enable=QtSvg"
configopts += " --enable=QtTest"
configopts += " --enable=QtWebKit"
#configopts += " --enable=QtWebKitWidgets"
#configopts += " --enable=QtWidgets"
configopts += " --enable=QtXml"
configopts += " --enable=QtXmlPatterns"
#configopts += " --enable=_QOpenGLFunctions_ES2"

the commented have missing dependencies on my system.

now in easybuild/software/PyQt/4.12-foss-2016b-Python-2.7.12/lib/python2.7/site-packages/PyQt4/ I have:

Qt.so
QtCore.so
QtDeclarative.so
QtDesigner.so
QtGui.so
QtHelp.so
QtMultimedia.so
QtNetwork.so
**QtOpenGL.so**
QtScript.so
QtScriptTools.so
QtSql.so
QtSvg.so
QtTest.so
QtWebKit.so
QtXml.so
QtXmlPatterns.so

**Comment by boegel** [comment] 2017-08-10 09:39
@iotaka Any idea why the auto-detection mechanism that would enable `QtOpenGL.so` is not working? Any clues in the configure output?

**Comment by iotaka** [comment] 2017-08-10 16:21
I was in a ssh without X

**Comment by boegel** [comment] 2017-08-10 17:35
That's how I usually install things, X forwarding is never enabled for me, so I doubt that's the cause...

**Comment by Micket** [comment] 2024-03-22 01:16
Qt4 is long since deprecated, this issue is well outdated. Closing.

**Closed by Micket** 2024-03-22 01:16 UTC
