### ISSUE TITLE
tcl error with sqlite3_analyzer

### ISSUE THREAD

**Issue by shahzebsiddiqui** [easybuilders/easybuild-easyconfigs#5164] opened 2017-09-22 18:16 UTC
```
[siddis14@amrndhl1295 bin]$ sqlite3_analyzer
can't find package sqlite3
    while executing
"package require sqlite3"
    (file "/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/Tcl/8.6.5/bin/sqlite3_analyzer" line 4)
```

Looks like sqlite3 package is not found, looking at post https://www.linuxquestions.org/questions/programming-9/can%27t-find-package-sqlite3-using-tcl-on-ubuntu-813157/ we need to install some packages. Shouldn't easybuild build these dependency or have it be os-dependency to install the package.

**Comment by boegel** [comment] 2017-09-23 08:28
@shahzebsiddiqui It seems like `SQLite` must be included as a dependency for `Tcl`.

Can you check whether loading an `SQLite` module fixes the problem you're seeing?

**Comment by shahzebsiddiqui** [comment] 2017-09-25 12:31
still not fix the problem.
```
[siddis14@amrndhl1295 ~]$ ml

Currently Loaded Modules:
  1) icc/.2017.1.132-GCC-5.4.0-2.27   3) binutils/.2.27                     5) impi/2017.1.132   7) intel/2017.01   9) Tcl/.8.6.5    11) libreadline/.6.3
  2) GCCcore/.5.4.0                   4) ifort/.2017.1.132-GCC-5.4.0-2.27   6) imkl/2017.1.132   8) zlib/.1.2.8    10) ncurses/.6.0  12) SQLite/.3.13.0

[siddis14@amrndhl1295 ~]$ sqlite3_analyzer
can't find package sqlite3
    while executing
"package require sqlite3"
    (file "/nfs/grid/software/RHEL7/easybuild/software/MPI/intel/2017.1.132-GCC-5.4.0-2.27/impi/2017.1.132/Tcl/8.6.5/bin/sqlite3_analyzer" line 4)


```

I also have the rpm not sure what is the issue
```

[siddis14@amrndhl1295 ~]$ rpm -qa | grep sqlite
sqlite-3.7.17-8.el7.x86_64

```

By the way I did not intend to find this error, I was just trying to do testing for each of these apps through buildtest and I came across this issue

**Comment by Micket** [comment] 2024-03-26 00:26
Testing recent sqlite3_analyzer and I can't reproduce any issues. Maybe there was something locally broken, or it was resolved in newer easyconfigs. Closing.

**Closed by Micket** 2024-03-26 00:26 UTC
