### ISSUE TITLE
Intel softwares: download URL changed

### ISSUE THREAD

**Issue by fenz** [easybuilders/easybuild-easyconfigs#11031] opened 2020-07-27 13:34 UTC
In seems intel changed one part of the url for downloading the softwares:
https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/i/iccifort/iccifort-2020.1.217.eb#L11
from .../irc_nas/... to .../IRC_NAS/...
so the builds are failing because the software can't be downloaded.
Can you please check and, in case, update the easyconfigs?

**Comment by boegel** [comment] 2020-08-03 13:14
I can confirm that the URL that Intel provides via their download site now uses `/IRC_NAS/` rather than `/irc_nas/`, but when checking now the previous `/irc_nas/` still works for me.

Probably Intel realized their mistake themselves, and added a symlink back?

**Comment by boegel** [comment] 2021-02-19 17:03
Closing, no longer valid, `irc_nas` URLs work fine (again)

**Closed by boegel** 2021-02-19 17:03 UTC
Labels: problem report
