### ISSUE TITLE
iccifort update5 does not respect components to install

### ISSUE THREAD

**Issue by fenz** [easybuilders/easybuild-easyconfigs#9478] opened 2019-12-11 12:24 UTC
I'm building this easyconfig: https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/i/iccifort/iccifort-2019.5.281.eb.
I think imkl, impi and other components that are not specified in the easyconfig should not be installed but they actually are. 
I didn't have this issue with the update 4, can anyone confirm the components list is respected by this new version?

**Comment by fenz** [comment] 2019-12-11 13:24
Just to complete the info, the update 4 (https://github.com/easybuilders/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/i/iccifort/iccifort-2019.4.243.eb) has the same list of components to install but while after building the iccifort-2019.4.243.eb the result is:
`$ du -sh ./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/*`
`168M	./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/bin`
`246M	./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/compiler`
`0		./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/documentation`
`0		./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/man`
`7.1M		./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/mpirt`
`0		./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/pkg_bin`
`512K	./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/pstl`
`65M		./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/tbb`

the result for after building iccifort-2019.5.281.eb is: 
`$ du -sh ./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/*`
`595M	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/bin`
`253M	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/compiler`
`3.3G	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/daal`
`0	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/documentation`
`3.7G	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/ipp`
`53M	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/lib`
`0	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/man`
`2.6G	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/mkl`
`62M	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/mpi`
`7.1M	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/mpirt`
`0	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/pkg_bin`
`672K	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/pstl`
`65M	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/tbb`

So daal, ipp, mkl, mpi get installed as well.
And outside this folder:
`$ du -sh ./iccifort/2019.5.281/*`                               
`4.0K	./iccifort/2019.5.281/bin`
`0	./iccifort/2019.5.281/compilers_and_libraries`
`152K	./iccifort/2019.5.281/compilers_and_libraries_2019`
`11G	./iccifort/2019.5.281/compilers_and_libraries_2019.5.281`
`343M	./iccifort/2019.5.281/conda_channel`
`0	./iccifort/2019.5.281/daal`
`184M	./iccifort/2019.5.281/debugger_2019`
`19M	./iccifort/2019.5.281/documentation_2019`
`428K	./iccifort/2019.5.281/easybuild`
`892K	./iccifort/2019.5.281/ide_support_2019`
`8.0K	./iccifort/2019.5.281/impi`
`0	./iccifort/2019.5.281/include`
`795M	./iccifort/2019.5.281/intelpython2`
`831M	./iccifort/2019.5.281/intelpython3`
`0	./iccifort/2019.5.281/ipp`
`0	./iccifort/2019.5.281/lib`
`0	./iccifort/2019.5.281/man`
`0	./iccifort/2019.5.281/mkl`
`0	./iccifort/2019.5.281/mpirt`
`0	./iccifort/2019.5.281/parallel_studio_xe_2019`
`43M	./iccifort/2019.5.281/parallel_studio_xe_2019.5.075`
`0	./iccifort/2019.5.281/pstl`
`16K	./iccifort/2019.5.281/samples_2019`
`0	./iccifort/2019.5.281/tbb`

you see intelpython was installed as well

**Comment by boegel** [comment] 2019-12-12 12:02
I can confirm I see the same issue when comparing the contents of the `iccifort/2019.4.243` installation directory vs `iccifort/2019.5.281`...

As far as I can tell EasyBuild is correctly passing the list of matching components (which does not include `impi`, `imkl`, etc.), but the Intel installer isn't honoring that.

**Comment by boegel** [comment] 2019-12-12 12:23
@fenz Is this mostly a matter of saving disk space for you, or are you running into problems cause the additional components are installed too?

In any case, this issue should be taken up with Intel support I think...

**Comment by fenz** [comment] 2019-12-12 14:14
I figured it out because of the space (since I'm building this inside containers) but my main concern is about conflicts. In fact I was interested in installing the intel toolchain but, since iccifort is already installing mpi and mkl, I guess I will end up in a completely messed environment when I install the intel toolchain (and that's what I want to avoid using EasyBuild).
Should I ask the intel support?

**Comment by bartoldeman** [comment] 2019-12-12 14:37
We can actually study `mediaconfig.xml` to see what has changed, and if mpi/mkl/python is a dependency of some component we specify..

**Comment by bartoldeman** [comment] 2019-12-12 15:49
I didn't see anything obvious (they've added the LLVM-based compiler but that seems to be ok). Won't have much more time to look at it today.

**Comment by fenz** [comment] 2019-12-12 16:00
Actually, something else I saw, in both update 4 and 5, there's a patch applied for not installing mpirt (that modifies the mediaconfig.xml) but it seems something about mpirt gets installed anyway:
`7.1M ./iccifort/2019.4.243/compilers_and_libraries_2019.4.243/linux/mpirt`
`7.1M ./iccifort/2019.5.281/compilers_and_libraries_2019.5.281/linux/mpirt`

I don't know if this is related or not but I thought it was worth to mention

**Comment by boegel** [comment] 2019-12-12 20:44
I think it's worth adding Intel support, alongside someone looking into `mediaconfig.xml` to see if we can sort it out ourselves.

We're basically running ` ./install.sh  -s silent.cfg`, with this as the contents of `silent.cfg`:

```
ACTIVATION_TYPE=license_server
ACTIVATION_LICENSE_FILE=/path/to/licenses/intel/license.lic
PSET_INSTALL_DIR=/tmp/test/software/iccifort/2019.5.281
ACCEPT_EULA=accept
INSTALL_MODE=NONRPM
CONTINUE_WITH_OPTIONAL_ERROR=yes
COMPONENTS=intel-comp__x86_64;intel-comp-32bit__x86_64;intel-comp-doc__noarch;intel-comp-l-all-common__noarch;intel-comp-l-all-vars__noarch;intel-comp-nomcu-vars__noarch;intel-comp-ps-32bit__x86_64;intel-comp-ps__x86_64;intel-comp-ps-ss__x86_64;intel-comp-ps-ss-bec__x86_64;intel-comp-ps-ss-bec-32bit__x86_64;intel-compxe__noarch;intel-compxe-doc__noarch;intel-ccompxe__noarch;intel-fcompxe__noarch;intel-icc__x86_64;intel-icc-32bit__x86_64;intel-icc-common__noarch;intel-icc-common-ps__noarch;intel-icc-common-ps-ss-bec__noarch;intel-icc-doc__noarch;intel-icc-doc-ps__noarch;intel-icc-ps__x86_64;intel-icc-ps-ss-bec__x86_64;intel-icc-ps-ss-bec-32bit__x86_64;intel-ifort__x86_64;intel-ifort-32bit__x86_64;intel-ifort-common__noarch;intel-ifort-doc__noarch;intel-openmp__x86_64;intel-openmp-32bit__x86_64;intel-openmp-common__noarch;intel-openmp-common-icc__noarch;intel-openmp-common-ifort__noarch;intel-openmp-ifort__x86_64;intel-openmp-ifort-32bit__x86_64;intel-ips__noarch;intel-ipsc__noarch;intel-gdb__x86_64;intel-gdb-source__noarch;intel-gdb-python-source__noarch;intel-gdb-common__noarch;intel-gdb-common-ps__noarch;intel-gdb-cdt-source__noarch
```

We could ask Intel support why that suddenly results in having `impi` & co (which are not listed in `COMPONENTS`) installed as well for 2019 update 5...

**Comment by henkela** [comment] 2020-01-31 09:33
Hi, 
I'd like to add just a bit of Info. Until icc/2019.0.018-GCC-7.3.0 I only see in compiler/icc/2019.0.018-GCC-7.3.0
```
bin                                 conda_channel       include  tbb
compilers_and_libraries             debugger_2019       lib
compilers_and_libraries_2019        documentation_2019  man
compilers_and_libraries_2019.0.117  ide_support_2019    pstl
```

Starting with icc/2019.3.199-GCC-8.3.0 it's
```
advisor                             inspector_2019
advisor_2019                        inspector_2019.3.0.591484
advisor_2019.3.0.591490             itac
bin                                 lib
clck                                man
clck_latest                         parallel_studio_xe_2019
compilers_and_libraries             parallel_studio_xe_2019.3.062
compilers_and_libraries_2019        performance_snapshot
compilers_and_libraries_2019.3.199  performance_snapshots
conda_channel                       performance_snapshots_2019.3.0.591499
debugger_2019                       pstl
documentation_2019                  samples_2019
easybuild                           tbb
ide_support_2019                    vtune_amplifier
include                             vtune_amplifier_2019
inspector                           vtune_amplifier_2019.3.0.591499

```
The patch for removing the mpi_rt dependency works for me however. 
Did somebody contact intel-support already?

**Comment by henkela** [comment] 2020-01-31 09:45
We also tried a manual install comparison (using a silent.cfg) once with components=DEFAULT and once COMPONENTS=intel-icc__x86_64;intel-icc-32bit__x86_64;intel-ifort__x86_64;intel-ifort-32bit__x86_64. 
This yielded an identical directory tree. But in the first case the total space is 16GB and in the latter it's only 3.1GB. But if I install iccifort with easybuild and components = ['intel-comp', 'intel-ccomp', 'intel-icc', 'intel-openmp', 'intel-ipsc?_', 'intel-gdb(?!.*mic)'] the folders (compilers_and_libraries_2019.5.28/linux/{mkl,mpi,mpirt,daal,ipp}are filled with the libs and bins...

**Comment by boegel** [comment] 2020-04-12 12:48
I got some feedback on this from Intel (not through an official support ticket, but from someone at Intel directly):

```
>>> Is this a known issue with PSXE 2019 update 5?

it is known issue. It was fixed in PSXE 2020
```

**Comment by boegel** [comment] 2022-06-04 19:23
I don't think there's anything we can do here, and as far as I know this isn't causing any trouble, except for wasted disk space, so closing this issue...

**Closed by boegel** 2022-06-04 19:23 UTC
Labels: bug report
