### ISSUE TITLE
g2clib-1.2.3 doesn't exist.

### ISSUE THREAD

**Issue by spikebike** [easybuilders/easybuild-easyconfigs#393] opened 2013-08-09 10:56 UTC
I wanted to install NCL which points at g2clib-1.2.3.

The target URL for the download only has 1.4.0 now. 

Not sure if the compatibility is perfect, but it looks like all references to  g2clib-1.2.3 should be changed to 1.4.0.

**Comment by boegel** [comment] 2021-04-06 19:06
closing this as duplicate of #12506

**Closed by boegel** 2021-04-06 19:06 UTC
Labels: bug report, software-specific
