### ISSUE TITLE
problem installing pytorch-1.2 and 1.3

### ISSUE THREAD

**Issue by danival36** [easybuilders/easybuild-easyconfigs#9337] opened 2019-11-19 18:23 UTC
Hi to all, 

I have a problem when I try to install pytorch (1.2 or 1.3 versions). Easybuild crashed at the building phase and always the same error: 

 exit code 1 and output:
**fatal: Not a git repo**
 I using this easyconfig file: PyTorch-1.3.1-foss-2019b-Python-3.7.4.eb

Does anyone have experienced the same error? 

Thanks a lot for your help!

D.

**Comment by akesandgren** [comment] 2019-11-19 19:48
@branfosj Any ideas on this?

@danival36 Exactly how did you try to build this? And with which version of EasyBuild?

**Comment by branfosj** [comment] 2019-11-19 20:39
Doing a search through my log for building the same easyconfig - with, hopefully, enough context to show where they appear:
```
== 2019-11-17 12:36:09,999 run.py:534 INFO cmd "PYTORCH_BUILD_VERSION=1.3.1 PYTORCH_BUILD_NUMBER=1 VERBOSE=1 LDFLAGS="$LDFLAGS -ldl" USE_FFMPEG=ON USE_IBVERBS=1 USE_GFLAGS=ON USE_GLOG=ON  /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-haswell/software/Python/3.7.4-GCCcore-8.3.0/bin/python setup.py build " exited with exit code 0 and output:
fatal: Not a git repository (or any parent up to mount point /dev/shm)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

```
-- USE_CUDNN is set to 0. Compiling without cuDNN support
disabling ROCM because NOT USE_ROCM is set
-- MIOpen not found. Compiling without MIOpen support
-- MKLDNN_THREADING = OMP:COMP
CMake Warning (dev) at third_party/ideep/mkl-dnn/cmake/options.cmake:33 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'MKLDNN_ENABLE_CONCURRENT_EXEC'.
Call Stack (most recent call first):
  third_party/ideep/mkl-dnn/cmake/utils.cmake:24 (include)
  third_party/ideep/mkl-dnn/CMakeLists.txt:74 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- OpenMP lib: provided by compiler
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- VTune profiling environment is unset
fatal: Not a git repository (or any parent up to mount point /dev/shm)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- Found MKL-DNN: TRUE
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
```

```
== 2019-11-17 13:06:19,418 run.py:534 INFO cmd "PYTORCH_BUILD_VERSION=1.3.1 PYTORCH_BUILD_NUMBER=1 VERBOSE=1 LDFLAGS="$LDFLAGS -ldl" USE_FFMPEG=ON USE_IBVERBS=1 USE_GFLAGS=ON USE_GLOG=ON  /rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-haswell/software/Python/3.7.4-GCCcore-8.3.0/bin/python setup.py install --prefix=/rds/bear-apps/devel/2019b/branfosj-eb-1/EL7/EL7-haswell/software/PyTorch/1.3.1-foss-2019b-Python-3.7.4 " exited with exit code 0 and output:
fatal: Not a git repository (or any parent up to mount point /dev/shm)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

The first and third of these are from invoking `setup.py` - at https://github.com/pytorch/pytorch/blob/v1.3.1/setup.py#L264 which is in a `try` / `except` block, so I'd expect that to be fine.

The second is from https://github.com/intel/mkl-dnn/blob/0125f28c61c1f822fd48570b4c1066f96fcb9b2e/cmake/version.cmake#L30 and I am unsure if the interaction between CMake and git could cause an issue (we should all have the same version of CMake as that is a build dependency).

@danival36 Are you able to provide us with the build log? Or can you look at it to let us know when in the build process this error is hit.

**Comment by boegel** [comment] 2019-11-27 20:26
closing as duplicate of #9344, where @danival36 mentioned that the installation worked out fine after fixing OpenSSL support in `cURL`...

**Closed by boegel** 2019-11-27 20:26 UTC
Labels: problem report
