### ISSUE TITLE
libX11-devel is still an osdependency for Tk-8.6.4-goolf-1.7.20-no-X11.eb ?

### ISSUE THREAD

**Issue by fgeorgatos** [easybuilders/easybuild-easyconfigs#3193] opened 2016-06-08 22:38 UTC
This was detected within an AWS instance:

```
/home/ec2-user/.local/easybuild/build/Tk/8.6.4/goolf-1.7.20-no-X11/tk8.6.4/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such fi
 #   include <X11/Xlib.h>
```

The error went away after a `yum install libX11-devel`, despite what the versionsuffix says...

**Comment by boegel** [comment] 2016-06-09 09:00
@fgeorgatos duplicate of #2261 ?

**Comment by fgeorgatos** [comment] 2016-06-25 23:20
almost duplicate: this has to be an issue across all Tk easyconfigs (goolf vs foss, here)
I leave it up to you to decide if you wish to consolidate these 2 issues, I'm neutral to either approach!

**Comment by boegel** [comment] 2017-09-06 20:51
@fgeorgatos No longer relevant since we now include the `X11` bundle as a dep for `Tk`?

**Closed** 2017-10-30 10:36 UTC
Labels: 2017b
