### ISSUE TITLE
Pylint easyconfig with Python 2.x broken?

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-easyconfigs#12596] opened 2021-04-14 08:34 UTC
When trying to install `Pylint-1.9.5-GCCcore-8.3.0-Python-2.7.16.eb` (cfr. #12076), I'm hitting this:

```
distutils.errors.DistutilsOptionError: find_namespace: directive is unsupported on Python < 3.3
```

How can this ever have worked for Python 2?!

@lexming @smoors Any ideas?

**Comment by lexming** [comment] 2021-04-14 09:38
I confirm that now it doesn't work on my side either. The error triggers with the extension `mccabe`, which has not seen any new commits since 2017. So this seems a regression caused a by a change somewhere else. The easyconfig Python 2.7.16 has not seen any new commits since https://github.com/easybuilders/easybuild-easyconfigs/pull/12076, so my first guess is the easyblock of Python.

**Comment by branfosj** [comment] 2021-04-14 09:42
I've also tried a build of this - I pick this line from the failure to install `mccabe`:
```
      File "/dev/shm/branfosj-admin/eb-97fbqp6p/easy_install-RSgWEg/pytest-runner-5.3.0/setup.py", line 21, in <module>
```
Where is that `pytest-runner` coming from? That is a version released in February this year.

**Comment by branfosj** [comment] 2021-04-14 09:52
And yes that is the issue. `pytest-runner` 5.3.0 has this in the change log: "Require Python 3.6 or later." Adding an explicit `pytest-runner` 5.2 to the Pylint ec allows it to build (`'modulename': 'ptr',`) - though that is likely a newer version than was used in #12076.

**Comment by lexming** [comment] 2021-04-14 10:10
@branfosj indeed, the issue is `pytest-runner`. It might have gone unnoticed because it is declared as a `setup_requires` and does not get installed in the installation directory of Pylint. So `pip` just downloads and uses it as a build dependency. The problem is that we do not have any good way to install those extensions as build dependencies. So we either patch the `setup.py` of `mccabe` and define a max version for `pytest-runner` or we install `pytest-runner` with Pylint.

**Closed** 2021-04-15 07:46 UTC
Labels: problem report
